#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GNB.Infrastructure.Data.Model
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Demo")]
	public partial class GNBDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public GNBDataDataContext() : 
				base(global::GNB.Infrastructure.Data.Properties.Settings.Default.DemoConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public GNBDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GNBDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GNBDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public GNBDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetRates")]
		public ISingleResult<GetRatesResult> GetRates()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetRatesResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.GetTransactions")]
		public ISingleResult<GetTransactionsResult> GetTransactions()
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
			return ((ISingleResult<GetTransactionsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsRates")]
		public int InsRates([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Rates", DbType="NVarChar(MAX)")] string rates)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), rates);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.InsTransactions")]
		public int InsTransactions([global::System.Data.Linq.Mapping.ParameterAttribute(Name="Transactions", DbType="NVarChar(MAX)")] string transactions)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), transactions);
			return ((int)(result.ReturnValue));
		}
	}
	
	public partial class GetRatesResult
	{
		
		private string _Rates;
		
		public GetRatesResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Rates", DbType="NVarChar(MAX)")]
		public string Rates
		{
			get
			{
				return this._Rates;
			}
			set
			{
				if ((this._Rates != value))
				{
					this._Rates = value;
				}
			}
		}
	}
	
	public partial class GetTransactionsResult
	{
		
		private string _Transactions;
		
		public GetTransactionsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Transactions", DbType="NVarChar(MAX)")]
		public string Transactions
		{
			get
			{
				return this._Transactions;
			}
			set
			{
				if ((this._Transactions != value))
				{
					this._Transactions = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
