//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GNB.Infrastructure.ServiceAgents.Webs.WcfGNB
{
    using System.Runtime.Serialization;
    using System;


    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "rates", Namespace = "http://schemas.datacontract.org/2004/07/GNB.WcfService.DataContract", ItemName = "rate")]
    [System.SerializableAttribute()]
    public class rates : System.Collections.Generic.List<GNB.Infrastructure.ServiceAgents.Webs.WcfGNB.rate>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "rate", Namespace = "http://schemas.datacontract.org/2004/07/GNB.WcfService.DataContract")]
    [System.SerializableAttribute()]
    public partial class rate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string fromField;

        private string toField;

        private string rateMemberField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string from
        {
            get
            {
                return this.fromField;
            }
            set
            {
                if ((object.ReferenceEquals(this.fromField, value) != true))
                {
                    this.fromField = value;
                    this.RaisePropertyChanged("from");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string to
        {
            get
            {
                return this.toField;
            }
            set
            {
                if ((object.ReferenceEquals(this.toField, value) != true))
                {
                    this.toField = value;
                    this.RaisePropertyChanged("to");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(Name = "rate", IsRequired = true, Order = 2)]
        public string rateMember
        {
            get
            {
                return this.rateMemberField;
            }
            set
            {
                if ((object.ReferenceEquals(this.rateMemberField, value) != true))
                {
                    this.rateMemberField = value;
                    this.RaisePropertyChanged("rateMember");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name = "transactions", Namespace = "http://schemas.datacontract.org/2004/07/GNB.WcfService.DataContract", ItemName = "transaction")]
    [System.SerializableAttribute()]
    public class transactions : System.Collections.Generic.List<GNB.Infrastructure.ServiceAgents.Webs.WcfGNB.transaction>
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "transaction", Namespace = "http://schemas.datacontract.org/2004/07/GNB.WcfService.DataContract")]
    [System.SerializableAttribute()]
    public partial class transaction : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
    {

        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;

        private string skuField;

        private string amountField;

        private string currencyField;

        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true)]
        public string sku
        {
            get
            {
                return this.skuField;
            }
            set
            {
                if ((object.ReferenceEquals(this.skuField, value) != true))
                {
                    this.skuField = value;
                    this.RaisePropertyChanged("sku");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 1)]
        public string amount
        {
            get
            {
                return this.amountField;
            }
            set
            {
                if ((object.ReferenceEquals(this.amountField, value) != true))
                {
                    this.amountField = value;
                    this.RaisePropertyChanged("amount");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute(IsRequired = true, Order = 2)]
        public string currency
        {
            get
            {
                return this.currencyField;
            }
            set
            {
                if ((object.ReferenceEquals(this.currencyField, value) != true))
                {
                    this.currencyField = value;
                    this.RaisePropertyChanged("currency");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "WcfGNB.IGNBService")]
    public interface IGNBService
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IGNBService/GetRateList", ReplyAction = "http://tempuri.org/IGNBService/GetRateListResponse")]
        GNB.Infrastructure.ServiceAgents.Webs.WcfGNB.rates GetRateList();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IGNBService/GetRateList", ReplyAction = "http://tempuri.org/IGNBService/GetRateListResponse")]
        System.Threading.Tasks.Task<GNB.Infrastructure.ServiceAgents.Webs.WcfGNB.rates> GetRateListAsync();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IGNBService/GetTransactionList", ReplyAction = "http://tempuri.org/IGNBService/GetTransactionListResponse")]
        GNB.Infrastructure.ServiceAgents.Webs.WcfGNB.transactions GetTransactionList();

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IGNBService/GetTransactionList", ReplyAction = "http://tempuri.org/IGNBService/GetTransactionListResponse")]
        System.Threading.Tasks.Task<GNB.Infrastructure.ServiceAgents.Webs.WcfGNB.transactions> GetTransactionListAsync();
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGNBServiceChannel : GNB.Infrastructure.ServiceAgents.Webs.WcfGNB.IGNBService, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GNBServiceClient : System.ServiceModel.ClientBase<GNB.Infrastructure.ServiceAgents.Webs.WcfGNB.IGNBService>, GNB.Infrastructure.ServiceAgents.Webs.WcfGNB.IGNBService
    {

        public GNBServiceClient()
        {
        }

        public GNBServiceClient(string endpointConfigurationName) :
                base(endpointConfigurationName)
        {
        }

        public GNBServiceClient(string endpointConfigurationName, string remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public GNBServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) :
                base(endpointConfigurationName, remoteAddress)
        {
        }

        public GNBServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public GNB.Infrastructure.ServiceAgents.Webs.WcfGNB.rates GetRateList()
        {
            return base.Channel.GetRateList();
        }

        public System.Threading.Tasks.Task<GNB.Infrastructure.ServiceAgents.Webs.WcfGNB.rates> GetRateListAsync()
        {
            return base.Channel.GetRateListAsync();
        }

        public GNB.Infrastructure.ServiceAgents.Webs.WcfGNB.transactions GetTransactionList()
        {
            return base.Channel.GetTransactionList();
        }

        public System.Threading.Tasks.Task<GNB.Infrastructure.ServiceAgents.Webs.WcfGNB.transactions> GetTransactionListAsync()
        {
            return base.Channel.GetTransactionListAsync();
        }
    }
}
